services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - lab-networks

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - lab-networks

networks:
  lab-networks:
    driver: bridge