name: Create Remote Backend

on:
    workflow_dispatch:
        inputs:
            environment:
                description: The environment to deploy
                type: choice
                required: true
                options:
                    - prod
                    - staging

jobs:
    deploy:
        uses: vinicius3516/terraform-bootstrap/.github/workflows/bootstrap.yml@main
        with:
            environment: ${{ github.event.inputs.environment }}
        secrets:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}